# render.yaml - PostgreSQL対応版
databases:
  - name: study-db
    databaseName: studydb
    user: study_user
    plan: free # or starter, standard, etc.

services:
  # 1. Web Service (Flask/Gunicorn)
  - type: web
    name: study-support-app
    runtime: python
    plan: free # or starter, standard, etc.
    buildCommand: "pip install -r requirements.txt"
    # データベースのマイグレーション/初期化を実行してからGunicornを起動
    startCommand: "python init_db.py && gunicorn --workers 2 --threads 2 --timeout 60 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false # Renderのダッシュボードで設定してください
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: study-db
          property: connectionString
    healthCheckPath: /health
    # 永続ディスクはPostgreSQLに移行したため不要

  # 2. Background Worker (Celery)
  - type: worker
    name: celery-worker
    runtime: python
    plan: free # or starter, standard, etc.
    buildCommand: "pip install -r requirements.txt"
    # webサービスと同様にDB初期化コマンドを含めることで、デプロイ順序の問題を回避
    startCommand: "python init_db.py && celery -A app.celery worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        fromService:
          type: web
          name: study-support-app
          envVarKey: OPENAI_API_KEY
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: study-db
          property: connectionString
    # 永続ディスクはPostgreSQLに移行したため不要

  # 3. Redis Instance (Celery Broker)
  - type: redis
    name: redis-broker
    plan: free # or starter, standard, etc.
    ipAllowList: [] # Render内のサービスからのみアクセスを許可
    maxmemoryPolicy: allkeys-lru

