# render.yaml - PostgreSQL対応版
databases:
  - name: study-db
    databaseName: studydb
    user: study_user
    plan: free # PostgreSQLは無料プランのまま

services:
  # 1. Web Service (Flask/Gunicorn)
  - type: web
    name: study-support-app
    runtime: python
    plan: Free # ユーザーの要求に応じて更新
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && gunicorn --workers 2 --threads 2 --timeout 60 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: study-db
          property: connectionString
    healthCheckPath: /health

  # 2. Background Worker (Celery)
  - type: worker
    name: celery-worker
    runtime: python
    plan: plan-srv-012 # ユーザーの要求に応じて更新
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && celery -A app.celery worker --loglevel=info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        fromService:
          type: web
          name: study-support-app
          envVarKey: OPENAI_API_KEY
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: study-db
          property: connectionString

  # 3. Redis Instance (Celery Broker)
  - type: redis
    name: redis-broker
    plan: starter # 既存のプランに合わせて 'starter' に変更
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru
